/**
 * Drug-parameter labels for text built on the server (notification email),
 * which cannot load the i18n bundles: `api/` is ESM and imports no JSON. A
 * copy of `parameters.*.label` in src/locales/{nb,en}.json, kept identical
 * by tests/api/parameterLabels.test.ts.
 */
import type { EmailLocale } from '../../src/lib/emailNotificationPrefs.js';

export const PARAMETER_LABELS: Record<EmailLocale, Record<string, string>> = {
  nb: {
    halfLife: 'Halveringstid',
    volumeOfDistribution: 'Vd',
    bioavailability: 'F',
    tmax: 'Tmax',
    cmax: 'Cmax',
    proteinBinding: 'Fb',
    bloodPlasmaRatio: 'B/P',
    pKa: 'pKa',
    nameNb: 'Norsk navn',
    nameEn: 'Engelsk navn',
    nameShort: 'Kortnavn',
    aliases: 'Aliaser',
    molecularWeight: 'MW',
    pubchemCid: 'PubChem CID',
    logP: 'logP',
    logD: 'logD',
    clearance: 'CL',
    ka: 'ka',
    vmax: 'Vmax',
    km: 'Km',
    postmortemRedistribution: 'C/P',
    pmAmRatio: 'PM/AM',
    dispositionModel: 'Disposisjon',
    eliminationModel: 'Eliminasjon',
    absorptionModel: 'Absorpsjon',
    ipmr: 'i-PMR',
    therapeuticDose: 'Terapeutisk dose',
    maxRecommendedDose: 'Maks anbefalt dose',
    nonMedicalDose: 'Ikke-medisinsk dose',
    overdoseDose: 'Overdosedose',
    fatalDose: 'Dødelig dose',
    therapeuticConcentration: 'Terapeutisk konsentrasjon',
    supratherapeuticConcentration: 'Supraterapeutisk konsentrasjon',
    impairmentConcentration: 'Påvirkningskonsentrasjon',
    toxicConcentration: 'Toksisk konsentrasjon',
    fatalConcentration: 'Dødelig konsentrasjon',
    bloodDetectionWindow: 'Blodvindu',
    oralFluidDetectionWindow: 'Spyttvindu',
    urineDetectionWindow: 'Urinvindu',
    analyteStability: 'Stabilitet',
  },
  en: {
    halfLife: 'Half-life',
    volumeOfDistribution: 'Vd',
    bioavailability: 'F',
    tmax: 'Tmax',
    cmax: 'Cmax',
    proteinBinding: 'Fb',
    bloodPlasmaRatio: 'B/P',
    pKa: 'pKa',
    nameNb: 'Name (Norwegian)',
    nameEn: 'Name (English)',
    nameShort: 'Short name',
    aliases: 'Aliases',
    molecularWeight: 'MW',
    pubchemCid: 'PubChem CID',
    logP: 'logP',
    logD: 'logD',
    clearance: 'CL',
    ka: 'ka',
    vmax: 'Vmax',
    km: 'Km',
    postmortemRedistribution: 'C/P',
    pmAmRatio: 'PM/AM',
    dispositionModel: 'Disposition',
    eliminationModel: 'Elimination',
    absorptionModel: 'Absorption',
    ipmr: 'i-PMR',
    therapeuticDose: 'Therapeutic dose',
    maxRecommendedDose: 'Max recommended dose',
    nonMedicalDose: 'Non-medical dose',
    overdoseDose: 'Overdose dose',
    fatalDose: 'Fatal dose',
    therapeuticConcentration: 'Therapeutic conc.',
    supratherapeuticConcentration: 'Supratherapeutic conc.',
    impairmentConcentration: 'Impairment conc.',
    toxicConcentration: 'Toxic conc.',
    fatalConcentration: 'Fatal conc.',
    bloodDetectionWindow: 'Blood window',
    oralFluidDetectionWindow: 'Oral-fluid window',
    urineDetectionWindow: 'Urine window',
    analyteStability: 'Stability',
  },
};
