/**
 * Registry ↔ catalog provenance report generator + CI gate.
 *
 *   npx tsx scripts/generate-registry-provenance.ts          # (re)write the report
 *   npx tsx scripts/generate-registry-provenance.ts --check  # fail on undeclared drift
 *
 * This is the author-time half of the harmonization plan's registry-provenance
 * follow-up (plan §18; `docs/kinetics-core/roadmap.md`). The reviewed catalog
 * `data/components.ts` is the single source; the frozen, checksummed
 * `src/lib/kinetics-core/registry.ts` is the pinned release the engine runs. This
 * script joins the two, classifies every catalog-checkable registry parameter,
 * and writes `docs/kinetics-core/registry-provenance.md`.
 *
 * The pure cross-check lives in `src/lib/kinetics-core/provenance.ts` (no catalog
 * import, so the core stays portable); this script supplies the real catalog and
 * does the file I/O. `--check` exits non-zero when any parameter declared to
 * track the catalog has drifted out of tolerance, or a checkable parameter has no
 * reviewed provenance — the same assertion the vitest suite makes, usable in CI
 * or a pre-vendor step.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  crossCheckRegistry,
  auditProvenanceCompleteness,
  reviewerAuthoredRouteParams,
  declaredMatrixTransforms,
  declaredObservationError,
  type CrossCheckReport,
  type CrossCheckRow,
} from '../src/lib/kinetics-core/provenance';
import { REGISTRY_VERSION, REGISTRY_CHECKSUM } from '../src/lib/kinetics-core/registry';
import { catalogLookup } from '../src/lib/kinetics-provenance/catalog-lookup';

const here = dirname(fileURLToPath(import.meta.url));
const REPORT_PATH = join(here, '..', 'docs', 'kinetics-core', 'registry-provenance.md');

function fmt(n: number | undefined): string {
  if (n === undefined) return '—';
  return Number.isInteger(n) ? String(n) : n.toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
}

function fmtRange(r: CrossCheckRow['catalog']): string {
  if (!r) return '—';
  const hasRange =
    r.min !== undefined && r.max !== undefined && r.min !== r.max;
  const parts: string[] = [];
  if (hasRange) parts.push(`${fmt(r.min)}–${fmt(r.max)}`);
  // Collapse a degenerate min===max range into the central value.
  const point = r.point ?? (r.min === r.max ? r.min : undefined);
  if (point !== undefined && (hasRange || parts.length === 0)) {
    parts.push(`~${fmt(point)}`);
  }
  return parts.join(' ') || '—';
}

const CLASS_LABEL: Record<CrossCheckRow['classification'], string> = {
  'within-range': 'within range',
  'near-point': 'near central',
  divergent: 'divergent',
  'no-catalog-value': 'no catalog value',
};

function renderReport(report: CrossCheckReport, completeness: string[]): string {
  const lines: string[] = [];
  lines.push('# kinetics-core registry — catalog provenance report');
  lines.push('');
  lines.push(
    '_Generated by `scripts/generate-registry-provenance.ts` — do not edit by hand._',
  );
  lines.push('');
  lines.push(
    `- **Registry release:** \`${REGISTRY_VERSION}\` (checksum \`${REGISTRY_CHECKSUM}\`)`,
  );
  lines.push(`- **Catalog source:** \`data/components.ts\``);
  lines.push(
    `- **Reference weight** (total-litre Vd conversion only): ${report.referenceWeightKg} kg`,
  );
  lines.push(
    `- **Relative tolerance** (near-central check): ${report.relTolerance}`,
  );
  lines.push('');
  lines.push(
    'Each row compares a frozen registry parameter against what the reviewed ' +
      'catalog says for the same analyte. `catalog`-sourced parameters must stay ' +
      'catalog-consistent (the gate); `reviewed-override` parameters intentionally ' +
      'depart and carry a rationale. Absorption (`kaPerHour`), the two-compartment ' +
      'micro-rates (`k12`/`k21`), and the Michaelis–Menten saturable-elimination ' +
      'parameters (`Vmax`/`Km`) are never in this cross-check: the catalog has no ' +
      'field for them, so they are always reviewer-authored (see the table above).',
  );
  lines.push('');

  lines.push('## Cross-check');
  lines.push('');
  lines.push(
    '| Analyte | Route | Parameter | Registry | Catalog | Result | Provenance | Note |',
  );
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const r of report.rows) {
    const source = r.provenance?.source ?? '**MISSING**';
    const flag = r.undeclaredDivergence ? ' ⚠️' : '';
    const note =
      r.provenance?.rationale ??
      (r.vdFromTotalLiters ? 'catalog Vd converted from total litres' : '');
    lines.push(
      `| ${r.analyte} | ${r.route} | ${r.param} | ${fmt(r.registryValue)} | ${fmtRange(
        r.catalog,
      )} | ${CLASS_LABEL[r.classification]}${flag} | ${source} | ${note} |`,
    );
  }
  lines.push('');

  lines.push('## Reviewer-authored route parameters (no catalog analogue)');
  lines.push('');
  lines.push(
    'Absorption rate, absorption lag, zero-order input duration, the mixed-input ' +
      'first-order fraction, and Vd-scaling mode cannot be cross-checked against the ' +
      'catalog, so they are recorded here — a change to any of them is a visible diff in ' +
      'this committed report (and `--check` fails on a stale report), not a silent switch.',
  );
  lines.push('');
  lines.push(
    '| Analyte | Route | Family | kaPerHour | tlag (h) | ZO input (h) | FO frac | k12/hr | k21/hr | Vmax (mg/L·h) | Km (mg/L) | Vd scaling |',
  );
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
  const authored = reviewerAuthoredRouteParams();
  for (const r of authored) {
    lines.push(
      `| ${r.analyte} | ${r.route} | ${r.family} | ${fmt(r.kaPerHour ?? undefined)} | ` +
        `${fmt(r.absorptionLagHours)} | ${fmt(r.zeroOrderDurationHours)} | ` +
        `${fmt(r.firstOrderFraction)} | ${fmt(r.k12PerHour)} | ${fmt(r.k21PerHour)} | ` +
        `${fmt(r.vmaxMgPerLPerHour)} | ${fmt(r.kmMgPerL)} | ${r.vdScaling ?? '—'} |`,
    );
  }
  lines.push('');

  // Parent/metabolite coupling (SC-3A): the formation/stoichiometry and per-species
  // disposition are ALL reviewer-authored — the catalog cross-check skips this family
  // entirely (it compares a single terminal-t½/Vd, which the family does not carry) —
  // so they get their own diffable table rather than collapsing to a checksum change.
  // The wide reviewer-authored table above has no columns for them; a dedicated table
  // keeps both readable.
  lines.push('## Parent/metabolite coupling (formation, stoichiometry & per-species disposition)');
  lines.push('');
  const pmRoutes = authored.filter((r) => r.family === 'parent-metabolite-first-order');
  if (pmRoutes.length === 0) {
    lines.push(
      '_No parent/metabolite model is registered yet — the first reviewed vertical is ' +
        'evidence-gated (SC-3B). The engine family (`parent-metabolite-first-order`) ships ' +
        'ahead of it; when a model is registered its formation fraction, molar masses, ' +
        'metabolite analyte and both species’ disposition appear here as a reviewable diff._',
    );
    lines.push('');
  } else {
    lines.push(
      '| Analyte | Route | Metabolite | fm | Parent MW (g/mol) | Metab MW (g/mol) | ' +
        'Parent t½ (h) | Parent Vd (L/kg) | Metab t½ (h) | Metab Vd (L/kg) |',
    );
    lines.push('|---|---|---|---|---|---|---|---|---|---|');
    for (const r of pmRoutes) {
      lines.push(
        `| ${r.analyte} | ${r.route} | ${r.metaboliteAnalyte ?? '—'} | ` +
          `${fmt(r.formationFraction)} | ${fmt(r.parentMolarMass)} | ${fmt(r.metaboliteMolarMass)} | ` +
          `${fmt(r.parentEliminationHalfLifeHours)} | ${fmt(r.parentVdLitersPerKg)} | ` +
          `${fmt(r.metaboliteEliminationHalfLifeHours)} | ${fmt(r.metaboliteVdLitersPerKg)} |`,
      );
    }
    lines.push('');
  }

  // Declared latent→observed matrix transforms (SC-5A): reviewed conversions with no
  // catalog analogue that rescale every reported concentration, so a change to a ratio
  // is a diffable decision here rather than a silent one.
  lines.push('## Declared matrix transforms (latent → observed)');
  lines.push('');
  const transforms = declaredMatrixTransforms();
  if (transforms.length === 0) {
    lines.push(
      '_No model declares a matrix transform yet — a reviewed whole-blood/plasma (or ' +
        'serum) conversion is evidence-gated per analyte (SC-5). The engine contract ' +
        'ships ahead of it; a cross-matrix request without a declared transform is ' +
        'refused rather than silently mislabelled, and any declared conversion appears ' +
        'here with its ratio and rationale as a reviewable diff._',
    );
    lines.push('');
  } else {
    lines.push('| Model | Analyte | From | To | Ratio | Rationale |');
    lines.push('|---|---|---|---|---|---|');
    for (const t of transforms) {
      lines.push(
        `| ${t.model} | ${t.analyte} | ${t.from} | ${t.to} | ${fmt(t.ratio)} | ${t.rationale} |`,
      );
    }
    lines.push('');
  }

  // Declared observation residual-error layers (SC-5B): reviewer-authored measurement-error
  // components with no catalog analogue that widen every reported band.
  lines.push('## Declared observation residual-error layers');
  lines.push('');
  const obsErr = declaredObservationError();
  if (obsErr.length === 0) {
    lines.push(
      '_No model declares an observation error layer yet — a reviewed assay/preanalytical/' +
        'biological/structural error model is evidence-gated per analyte (SC-5). The engine ' +
        'contract ships ahead of it; when declared, each layer widens the reported bands ' +
        '(the median is unchanged) and appears here with its CV/SD and rationale as a ' +
        'reviewable diff._',
    );
    lines.push('');
  } else {
    lines.push('| Model | Analyte | Layer | Proportional CV | Additive SD (mg/L) | Rationale |');
    lines.push('|---|---|---|---|---|---|');
    for (const e of obsErr) {
      lines.push(
        `| ${e.model} | ${e.analyte} | ${e.layer} | ${fmt(e.proportionalCv)} | ` +
          `${fmt(e.additiveSd)} | ${e.rationale} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Gate');
  lines.push('');
  if (report.undeclared.length === 0) {
    lines.push(
      '✅ No undeclared divergence: every catalog-tracking parameter is within ' +
        'tolerance and every checkable parameter is reviewed.',
    );
  } else {
    lines.push(
      `❌ ${report.undeclared.length} undeclared divergence(s) — a \`catalog\` ` +
        'parameter drifted, or a checkable parameter is unreviewed:',
    );
    lines.push('');
    for (const r of report.undeclared) {
      lines.push(
        `- **${r.analyte} ${r.route} ${r.param}**: registry ${fmt(
          r.registryValue,
        )} vs catalog ${fmtRange(r.catalog)} (${CLASS_LABEL[r.classification]})`,
      );
    }
  }
  lines.push('');
  if (completeness.length > 0) {
    lines.push('## Completeness problems');
    lines.push('');
    for (const p of completeness) lines.push(`- ${p}`);
    lines.push('');
  }

  lines.push('## Structural limitation (why the catalog cannot author the whole registry)');
  lines.push('');
  lines.push(
    'A drug-monograph row is not automatically a runnable model (plan §3). The ' +
      'catalog cannot supply: a first-order absorption rate (`kaPerHour`); ' +
      'inter-compartmental micro-rates or saturable-elimination constants ' +
      '(`k12`/`k21`, `Vmax`/`Km`); a ' +
      'per-route bioavailability split (it carries one absolute F); or clean, ' +
      'unit-consistent values for every analyte (several fields are noisy ' +
      'auto-extractions). So the registry stays hand-authored and reviewed, and ' +
      'this report enforces the guarantee the plan actually needs: no *silent* ' +
      'drift between a shipped parameter and the reviewed catalog.',
  );
  lines.push('');
  lines.push('## DB-derived offline registry artifact (CV-4c-2b-b-2)');
  lines.push('');
  lines.push(
    '`scripts/generate-derived-registry.ts` reads all derivation inputs in the single ' +
      '`REPEATABLE READ` transaction owned by `readDerivedRegistrySnapshot`, then commits a ' +
      'deterministic artifact to `src/lib/kinetics-core/generated-registry.ts`. Run `npm run ' +
      'kinetics:registry` to refresh it and `npm run kinetics:registry:check` for the non-writing ' +
      'live-DB comparison that runs beside this provenance gate in CI.',
  );
  lines.push('');
  lines.push(
    'The artifact contains its checksum, derived tier, override-supersession report, and an explicit ' +
      '`notModelable` report with each omitted entry’s overall and per-route missing/unsupported ' +
      'reasons. The offline loader recomputes the checksum and merges reviewed definitions first, ' +
      'so reviewed overrides always win.',
  );
  lines.push('');
  lines.push(
    'Rollout is opt-in with `VITE_DERIVED_REGISTRY_ENABLED=true`; until enabled, consumers keep the ' +
      'reviewed-only registry while the committed coverage report remains inspectable.',
  );
  lines.push('');
  return lines.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const report = crossCheckRegistry(catalogLookup);
  const completeness = auditProvenanceCompleteness();
  const markdown = renderReport(report, completeness);

  const failed = report.undeclared.length > 0 || completeness.length > 0;

  if (check) {
    const existing = safeRead(REPORT_PATH);
    if (existing !== markdown) {
      console.error(
        'registry-provenance.md is stale — run: npx tsx scripts/generate-registry-provenance.ts',
      );
    }
    if (failed) {
      console.error('Registry provenance gate FAILED:');
      for (const r of report.undeclared) {
        console.error(
          `  ${r.analyte} ${r.route} ${r.param}: registry ${r.registryValue} vs catalog ${fmtRange(
            r.catalog,
          )} (${r.classification})`,
        );
      }
      for (const p of completeness) console.error(`  ${p}`);
    }
    if (failed || existing !== markdown) process.exit(1);
    console.log('Registry provenance gate OK.');
    return;
  }

  writeFileSync(REPORT_PATH, markdown);
  console.log(`Wrote ${REPORT_PATH}`);
  if (failed) {
    console.warn(
      `WARNING: ${report.undeclared.length} undeclared divergence(s), ${completeness.length} completeness problem(s).`,
    );
    process.exit(1);
  }
}

function safeRead(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

main();
