/** Generate/check the offline DB-derived kinetics registry from one REPEATABLE READ snapshot. */
import 'dotenv/config';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readDerivedRegistrySnapshot } from '../api/_lib/model-derivation-store';
import { registeredAnalytes, findModel } from '../src/lib/kinetics-core/registry';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'kinetics-core', 'generated-registry.ts');
const check = process.argv.includes('--check');

function reviewedCount(): number {
  return registeredAnalytes().length;
}

function render(value: unknown): string {
  return `/** Generated by scripts/generate-derived-registry.ts; do not edit. */\nimport type { GeneratedRegistryArtifact } from './generated-registry-loader.js';\n\nexport const GENERATED_REGISTRY_ARTIFACT = ${JSON.stringify(value, null, 2)} as const satisfies GeneratedRegistryArtifact;\n`;
}

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
const build = await readDerivedRegistrySnapshot();
const overrideAnalytes = registeredAnalytes();
for (const analyte of overrideAnalytes) {
  const resolved = build.snapshot.definitions.find((definition) => definition.analyte === analyte);
  if (resolved !== findModel(analyte)) {
    // Snapshot deep-clones, so identity differs; compare the authoritative payload instead.
    if (JSON.stringify(resolved) !== JSON.stringify(findModel(analyte))) {
      throw new Error(`reviewed override lost precedence for ${analyte}`);
    }
  }
}
const artifact = {
  formatVersion: 1,
  generatedAt: 'snapshot-content-addressed',
  registryVersion: build.snapshot.version,
  checksum: build.snapshot.checksum,
  derivedDefinitions: build.snapshot.definitions.slice(reviewedCount()),
  derivedGrades: build.derivedGrades,
  supersededByOverride: build.snapshot.supersededByOverride,
  notModelable: build.notModelable,
};
const next = render(artifact);
if (check) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== next) {
    console.error('Generated registry artifact is stale. Run npm run kinetics:registry.');
    process.exitCode = 1;
  } else console.log(`Generated registry is current (${artifact.checksum}).`);
} else {
  writeFileSync(OUT, next);
  console.log(`Wrote ${OUT} (${artifact.checksum}, ${artifact.derivedDefinitions.length} derived, ${artifact.notModelable.length} not modelable).`);
}
